version: '3.1'

services:
  joomla:
    image: joomla
    restart: always
    ports:
      - 80:80
    environment:
      JOOMLA_DB_HOST: ${host}
      JOOMLA_DB_PASSWORD: ${pass}
      JOOMLA_DB_USER: ${user}
      JOOMLA_DB_NAME: ${db}
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
